### ISSUE TITLE
[CENÁRIO 2.2.2] Mudança na regra na execução da operação de crédito (Y001)

### ISSUE THREAD

**Issue by matheus-cardoso-deel** [IgorMarques/ATM-Exercise#19]
Alteração na operação de débito para que seja informada uma descrição para a operação.

**Comment by IgorMarques** [comment]
Entrando na etapa de análise de custo benefício

**Comment by IgorMarques** [comment]
Análise concluída: Viável

Prioridade definida

**Comment by IgorMarques** [comment]
**APROVADA PELO CCM**

**Comment by IgorMarques** [comment]
Entrando na etapa de documentar especificação

**Comment by IgorMarques** [comment]
**DOCUMENTAÇÃO DA IMPLEMENTAÇÃO**

_descricao detalhada da implementação que apenas desenvolvedores vao conseguir ler_

Desenvolvedor atribuído: @lucasbibiano

**Comment by lucasbibiano** [comment]
Finalizada implementação

**Comment by IgorMarques** [comment]
Entrando na etapa de validação

**Comment by IgorMarques** [comment]
Validada pelo gerente

**Comment by matheus-cardoso-deel** [comment]
Validada pelo cliente.

**Comment by IgorMarques** [comment]
Validada. Aguardando Integração

**Comment by IgorMarques** [comment]
Integrada
