### ISSUE TITLE
[CENÁRIO 2.3] Bug na funcionalidade bônus

### ISSUE THREAD

**Issue by matheus-cardoso-deel** [IgorMarques/ATM-Exercise#20]
O bônus deve ser de 3% do valor de cada operação.

**Comment by IgorMarques** [comment]
Entrando na etapa de análise de custo benefício

**Comment by IgorMarques** [comment]
Análise concluída: Bug confirmado e solução viável

Prioridade definida

**Comment by IgorMarques** [comment]
**APROVADA PELO CCM**

**Comment by IgorMarques** [comment]
Entrando na etapa de documentar especificação

**Comment by IgorMarques** [comment]
**DOCUMENTAÇÃO DA IMPLEMENTAÇÃO**

_descricao detalhada da implementação que apenas desenvolvedores vao conseguir ler_

Desenvolvedor atribuído: @lucasbibiano

**Comment by lucasbibiano** [comment]
Finalizada implementação

**Comment by IgorMarques** [comment]
Entrando em etapa de validação

**Comment by IgorMarques** [comment]
Validada pelo gerente

**Comment by matheus-cardoso-deel** [comment]
Validada pelo cliente.

**Comment by IgorMarques** [comment]
Validada. Aguardando integração

**Comment by IgorMarques** [comment]
Integrada
