### ISSUE TITLE
[CENÁRIO 2.5] Aprimoramento na operação de crédito em poupança

### ISSUE THREAD

**Issue by matheus-cardoso-deel** [IgorMarques/ATM-Exercise#22]
Inclusão da seguinte mensagem ao efetuar a operação de crédito em poupança: “Crédito no valor XX para a conta YY realizado com sucesso”.

**Comment by IgorMarques** [comment]
Entrando na etapa de análise de custo benefício

**Comment by IgorMarques** [comment]
Análise concluída: Viável.

Prioridade definida.

**Comment by IgorMarques** [comment]
**APROVADA PELO CCM**

**Comment by IgorMarques** [comment]
Entrando na etapa de documentar especificação

**Comment by IgorMarques** [comment]
**DOCUMENTAÇÃO DA IMPLEMENTAÇÃO**

_descricao detalhada da implementação que apenas desenvolvedores vao conseguir ler_

Desenvolvedor atribuído: @lucasbibiano

**Comment by IgorMarques** [comment]
Entrando na etapa de validação

**Comment by IgorMarques** [comment]
Erro na mensagem. A mesma deveria ser:

"Crédito no valor XX para a poupança YY foi realizado com sucesso”

**Comment by lucasbibiano** [comment]
Finalizada implementação

**Comment by IgorMarques** [comment]
Entrando novamente em validação

**Comment by IgorMarques** [comment]
Validada pelo gerente

**Comment by matheus-cardoso-deel** [comment]
Validade pelo cliente.

**Comment by IgorMarques** [comment]
Validada. Aguardando integração

**Comment by IgorMarques** [comment]
Integrada
